//-----------------------------------------------------------------------------------------
// uri (header only)
// Copyright (C) 2024 Fix8 Market Technologies Pty Ltd
//   by David L. Dight
// see https://github.com/fix8mt/uri
//
// Lightweight header-only C++20 URI parser
//
// Distributed under the Boost Software License, Version 1.0 August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------------------
#include <iostream>
#include <stdexcept>
#include <memory>
#include <string_view>
#include <fix8/uri.hpp>

//-----------------------------------------------------------------------------------------
using namespace FIX8;
using namespace std::literals::string_view_literals;

//-----------------------------------------------------------------------------------------
int main(int argc, char *argv[])
{
	constexpr std::string_view s1 { "https://dakka@www.blah.com:3000/" };
	constexpr basic_uri u1{s1};
	std::cout << u1.get_uri() << '\t' << '(' << sizeof(u1) << ')' << '\n';
	uri u2{s1};
	std::cout << u2.get_uri() << '\t' << '(' << sizeof(u2) << ')' << '\n';

	constexpr uri_static_immutable u3{"https://user:password@example.com/path?search=1"};
	std::cout << u3.get_uri() << '\t' << '(' << sizeof(u3) << ')' << '\n';
	uri u3a{"https://user:password@example.com/path?search=1"};
	std::cout << u3a.get_uri() << '\t' << '(' << sizeof(u3a) << ')' << '\n';

	uri u4{"https://example.org/./a/../b/./c"};
	std::cout << u4.get_uri() << '\t' << '(' << sizeof(u4) << ')' << '\n';

	return 0;
}

